string.o: string.c string.h
	gcc -Wall -g -c -o $@ $<

hash_table.o: hash_table.c hash_table.h
	gcc -Wall -g -c -o $@ $<

vector.o: vector.c vector.h
	gcc -Wall -g -c -o $@ $<

seg_vector.o: seg_vector.c seg_vector.h vector.h
	gcc -Wall -g -c -o $@ $<